[package]
name = "crony-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
crony-domain = { path = "../crony-domain" }
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
